/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ["images.unsplash.com"],
  },
  async redirects() {
    return [
      // Keep legacy redirect
      { source: '/digital-marketing', destination: '/home', permanent: true },

      // Disable template/irrelevant routes by redirecting to /home
      { source: '/about-dark', destination: '/home', permanent: true },
      { source: '/blog-dark', destination: '/home', permanent: true },
      { source: '/blog-v2', destination: '/home', permanent: true },
      { source: '/blog-v2-dark', destination: '/home', permanent: true },
      { source: '/category', destination: '/home', permanent: true },
      { source: '/category-dark', destination: '/home', permanent: true },
      { source: '/blog-details', destination: '/home', permanent: true },
      { source: '/blog-details-dark', destination: '/home', permanent: true },
      { source: '/career-dark', destination: '/career', permanent: true },
      { source: '/job-details', destination: '/career', permanent: true },
      { source: '/job-details-dark', destination: '/career', permanent: true },
      { source: '/contact-dark', destination: '/contact', permanent: true },
      { source: '/creative-agency', destination: '/home', permanent: true },
      { source: '/creative-agency-dark', destination: '/home', permanent: true },
      { source: '/design-studio', destination: '/home', permanent: true },
      { source: '/design-studio-dark', destination: '/home', permanent: true },
      { source: '/digital-agency', destination: '/home', permanent: true },
      { source: '/digital-agency-dark', destination: '/home', permanent: true },
      { source: '/digital-marketing-dark', destination: '/home', permanent: true },
      { source: '/error', destination: '/home', permanent: true },
      { source: '/error-dark', destination: '/home', permanent: true },
      { source: '/faq-dark', destination: '/faq', permanent: true },
      { source: '/modern-agency', destination: '/home', permanent: true },
      { source: '/modern-agency-dark', destination: '/home', permanent: true },
      { source: '/personal-portfolio', destination: '/home', permanent: true },
      { source: '/personal-portfolio-dark', destination: '/home', permanent: true },
      { source: '/portfolio-dark', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v2', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v2-dark', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v3', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v3-dark', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v4', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v4-dark', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v5', destination: '/portfolio', permanent: true },
      { source: '/portfolio-v5-dark', destination: '/portfolio', permanent: true },
      { source: '/portfolio-details', destination: '/portfolio', permanent: true },
      { source: '/portfolio-details-dark', destination: '/portfolio', permanent: true },
      { source: '/service-dark', destination: '/service', permanent: true },
      { source: '/service-v2', destination: '/service', permanent: true },
      { source: '/service-v2-dark', destination: '/service', permanent: true },
      { source: '/service-v3', destination: '/service', permanent: true },
      { source: '/service-v3-dark', destination: '/service', permanent: true },
      { source: '/service-v4', destination: '/service', permanent: true },
      { source: '/service-v4-dark', destination: '/service', permanent: true },
      { source: '/service-v5', destination: '/service', permanent: true },
      { source: '/service-v5-dark', destination: '/service', permanent: true },
      { source: '/service-v6', destination: '/service', permanent: true },
      { source: '/service-v6-dark', destination: '/service', permanent: true },
      { source: '/service-details', destination: '/service', permanent: true },
      { source: '/service-details-dark', destination: '/service', permanent: true },
      { source: '/startup-agency', destination: '/home', permanent: true },
      { source: '/startup-agency-dark', destination: '/home', permanent: true },
      { source: '/team-dark', destination: '/team', permanent: true },
      { source: '/team-details', destination: '/team', permanent: true },
      { source: '/team-details-dark', destination: '/team', permanent: true },
    ];
  },
};

module.exports = nextConfig;
